[build]
  command = "npm run build"
  publish = "."

[build.environment]
  NODE_VERSION = "18"
  BUILD_TIME = ""

# Ensure build script runs and creates commit info
[build.processing]
  skip_processing = false

[[redirects]]
  from = "/contact"
  to = "/#contact"
  status = 301

# Form handling configuration
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"

# Ensure .well-known directory is accessible
[[headers]]
  for = "/.well-known/*"
  [headers.values]
    Cache-Control = "no-cache"
